"use client";

import { Award, BookCheck, Flame, TrendingUp } from "lucide-react";
import { useAppState } from "@/components/app-provider";
import { PageHeader, ProgressBar, SectionTitle, StatCard } from "@/components/ui";
import { grammarTopics } from "@/data/grammar";
import { vocabulary } from "@/data/vocabulary";
import { calculateStreak } from "@/lib/learning/streak";

const average = (values: number[]) => values.length ? Math.round(values.reduce((a, b) => a + b, 0) / values.length) : 0;
export default function ProgressPage() {
  const { state } = useAppState(); const vocabularyMastery = average(state.vocabularyProgress.map((item) => item.mastery.overall)); const grammarMastery = average(state.grammarProgress.map((item) => item.mastery));
  const weak = state.grammarProgress.flatMap((progress) => { const topic = grammarTopics.find((item) => item.id === progress.topicId); return topic?.subtopics.map((item) => ({ title: item.title, parent: topic.title, score: progress.subtopicMastery[item.id] ?? 0 })) ?? []; }).sort((a, b) => a.score - b.score).slice(0, 5);
  return <><PageHeader eyebrow="Learning analytics" title="Progress" description="See what is durable, what is improving, and where your next focused practice will have the greatest effect."/><div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard icon={<BookCheck size={19}/>} label="Words learned" value={state.vocabularyProgress.length} detail={`of ${vocabulary.length} available`}/><StatCard icon={<Award size={19}/>} label="Words mastered" value={state.vocabularyProgress.filter((item) => item.mastery.overall >= 85).length}/><StatCard icon={<TrendingUp size={19}/>} label="Topics mastered" value={state.grammarProgress.filter((item) => item.mastery >= 85).length}/><StatCard icon={<Flame size={19}/>} label="Study streak" value={`${calculateStreak(state.activities)} days`}/></div><div className="page-grid"><section className="card p-5 lg:col-span-7"><SectionTitle title="Mastery overview" subtitle="Weighted by active knowledge"/><div className="space-y-5">{[["Vocabulary", vocabularyMastery, "#17795b"], ["Grammar", grammarMastery, "#5278bb"], [`CEFR ${state.settings.currentLevel} progress`, 42, "#d7922c"]].map(([label, score, color]) => <div key={String(label)}><div className="mb-2 flex justify-between text-sm"><b>{label}</b><b>{score}%</b></div><ProgressBar value={Number(score)} color={String(color)}/></div>)}</div><div className="mt-7 grid grid-cols-7 items-end gap-2 border-b border-[#dce6e1] pt-4">{[45, 58, 52, 70, 64, 81, 77].map((height, index) => <div key={index} className="text-center"><div className="mx-auto w-full max-w-10 rounded-t-md bg-[#badbce]" style={{ height }}/><span className="muted mt-1 block text-[9px]">{["M", "T", "W", "T", "F", "S", "S"][index]}</span></div>)}</div></section><section className="card p-5 lg:col-span-5"><SectionTitle title="Weak subtopics" subtitle="Specific skills below your target"/><div className="space-y-3">{weak.map((item) => <div key={`${item.parent}-${item.title}`}><div className="flex justify-between gap-3 text-sm"><div><b>{item.title}</b><div className="muted text-xs">{item.parent}</div></div><b className="text-amber-700">{item.score}%</b></div><div className="mt-1.5"><ProgressBar value={item.score} color="#d7922c"/></div></div>)}</div></section><section className="card p-5 lg:col-span-12"><SectionTitle title="Recent activity"/><div className="grid gap-2 md:grid-cols-3">{state.activities.slice(0, 6).map((item) => <div key={item.id} className="rounded-xl bg-[#f5f8f6] p-3"><div className="flex justify-between"><b className="text-sm">{item.label}</b><span className="badge">{Math.round(item.correct / item.total * 100)}%</span></div><div className="muted mt-2 text-xs">{new Date(item.date).toLocaleDateString()} · {item.correct}/{item.total} correct{item.minutes ? ` · ${item.minutes} min` : ""}</div></div>)}</div></section></div></>;
}
