ALTER TABLE "exercise_templates" ADD CONSTRAINT "exercise_difficulty_valid" CHECK ("exercise_templates"."difficulty" between 1 and 5);--> statement-breakpoint
ALTER TABLE "expression_progress" ADD CONSTRAINT "expression_mastery_valid" CHECK ("expression_progress"."mastery" between 0 and 100);--> statement-breakpoint
ALTER TABLE "grammar_progress" ADD CONSTRAINT "grammar_mastery_valid" CHECK ("grammar_progress"."mastery" between 0 and 100);--> statement-breakpoint
ALTER TABLE "learning_preferences" ADD CONSTRAINT "preferences_targets_valid" CHECK ("learning_preferences"."daily_target" between 10 and 60 and "learning_preferences"."max_new_words_per_day" between 0 and 20 and "learning_preferences"."max_new_grammar_per_day" between 0 and 3);--> statement-breakpoint
ALTER TABLE "learning_preferences" ADD CONSTRAINT "preferences_retention_valid" CHECK ("learning_preferences"."desired_retention" between 0.8 and 0.97);--> statement-breakpoint
ALTER TABLE "learning_preferences" ADD CONSTRAINT "preferences_language_valid" CHECK ("learning_preferences"."interface_language" in ('en', 'vi'));--> statement-breakpoint
ALTER TABLE "mistakes" ADD CONSTRAINT "mistake_repeat_count_valid" CHECK ("mistakes"."repeat_count" > 0);--> statement-breakpoint
ALTER TABLE "review_states" ADD CONSTRAINT "review_state_values_valid" CHECK ("review_states"."difficulty" between 1 and 10 and "review_states"."stability" >= 0 and "review_states"."scheduled_days" >= 0 and "review_states"."elapsed_days" >= 0 and "review_states"."review_count" >= 0 and "review_states"."correct_count" >= 0 and "review_states"."incorrect_count" >= 0 and "review_states"."lapses" >= 0 and "review_states"."version" >= 0);--> statement-breakpoint
ALTER TABLE "study_sessions" ADD CONSTRAINT "study_session_counts_valid" CHECK ("study_sessions"."correct" >= 0 and "study_sessions"."total" >= "study_sessions"."correct" and "study_sessions"."minutes" >= 0);--> statement-breakpoint
ALTER TABLE "study_sessions" ADD CONSTRAINT "study_session_time_valid" CHECK ("study_sessions"."completed_at" is null or "study_sessions"."completed_at" >= "study_sessions"."started_at");--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_email_normalized" CHECK ("users"."email" = lower(btrim("users"."email")));--> statement-breakpoint
ALTER TABLE "vocabulary_progress" ADD CONSTRAINT "vocabulary_mastery_valid" CHECK ("vocabulary_progress"."recognition" between 0 and 100 and "vocabulary_progress"."recall" between 0 and 100 and "vocabulary_progress"."context" between 0 and 100 and "vocabulary_progress"."spelling" between 0 and 100 and "vocabulary_progress"."overall" between 0 and 100);