import { sql } from "drizzle-orm";
import { boolean, check, doublePrecision, index, integer, jsonb, pgEnum, pgTable, primaryKey, real, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };
export const cefrLevel = pgEnum("cefr_level", ["A1", "A2", "B1", "B2", "C1", "C2"]);
export const knowledgeType = pgEnum("knowledge_type", ["vocabulary", "grammar", "expression"]);
export const reviewStatus = pgEnum("review_status", ["new", "learning", "review", "relearning"]);
export const expressionKind = pgEnum("expression_kind", ["idiom", "phrasal-verb", "collocation", "common-expression"]);
export const pathItemStatus = pgEnum("path_item_status", ["needs-foundation", "recommended", "in-progress", "reviewing", "strong", "mastered", "locked"]);

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), email: text("email").notNull(), passwordHash: text("password_hash").notNull(), emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }), ...timestamps,
}, (table) => [uniqueIndex("users_email_unique").on(table.email), check("users_email_normalized", sql`${table.email} = lower(btrim(${table.email}))`)]);

export const authSessions = pgTable("auth_sessions", {
  tokenHash: text("token_hash").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [index("auth_sessions_user_idx").on(table.userId), index("auth_sessions_expiry_idx").on(table.expiresAt)]);

export const passwordResetTokens = pgTable("password_reset_tokens", {
  tokenHash: text("token_hash").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [index("password_reset_user_idx").on(table.userId), index("password_reset_expiry_idx").on(table.expiresAt)]);

export const emailVerificationTokens = pgTable("email_verification_tokens", {
  tokenHash: text("token_hash").primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [index("email_verification_user_idx").on(table.userId), index("email_verification_expiry_idx").on(table.expiresAt)]);

export const learningPreferences = pgTable("learning_preferences", {
  userId: uuid("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), currentLevel: cefrLevel("current_level").default("B1").notNull(), dailyTarget: integer("daily_target").default(25).notNull(), maxNewWordsPerDay: integer("max_new_words_per_day").default(10).notNull(), maxNewGrammarPerDay: integer("max_new_grammar_per_day").default(1).notNull(), desiredRetention: real("desired_retention").default(0.9).notNull(), studyIntensity: text("study_intensity").default("balanced").notNull(), interfaceLanguage: text("interface_language").default("en").notNull(), showVietnamese: boolean("show_vietnamese").default(true).notNull(), onboardingCompletedAt: timestamp("onboarding_completed_at", { withTimezone: true }), ...timestamps,
}, (table) => [check("preferences_targets_valid", sql`${table.dailyTarget} between 10 and 60 and ${table.maxNewWordsPerDay} between 0 and 20 and ${table.maxNewGrammarPerDay} between 0 and 3`), check("preferences_retention_valid", sql`${table.desiredRetention} between 0.8 and 0.97`), check("preferences_language_valid", sql`${table.interfaceLanguage} in ('en', 'vi')`)]);

export const contentVersions = pgTable("content_versions", { id: uuid("id").defaultRandom().primaryKey(), version: text("version").notNull(), checksum: text("checksum").notNull(), publishedAt: timestamp("published_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex("content_versions_version_unique").on(table.version)]);
export const vocabularyContent = pgTable("vocabulary_content", { id: uuid("id").defaultRandom().primaryKey(), contentId: text("content_id").notNull(), word: text("word").notNull(), lemma: text("lemma"), partOfSpeech: text("part_of_speech").notNull(), level: cefrLevel("level").notNull(), frequencyRank: integer("frequency_rank"), frequencyBand: text("frequency_band"), topics: text("topics").array().default([]).notNull(), tags: text("tags").array().default([]).notNull(), active: boolean("active").default(true).notNull(), contentVersionId: uuid("content_version_id").references(() => contentVersions.id, { onDelete: "set null" }), ...timestamps }, (table) => [uniqueIndex("vocabulary_content_id_unique").on(table.contentId), index("vocabulary_word_idx").on(table.word), index("vocabulary_level_frequency_idx").on(table.level, table.frequencyRank)]);
export const vocabularyMeanings = pgTable("vocabulary_meanings", { id: uuid("id").defaultRandom().primaryKey(), vocabularyId: uuid("vocabulary_id").notNull().references(() => vocabularyContent.id, { onDelete: "cascade" }), position: integer("position").notNull(), englishDefinition: text("english_definition").notNull(), vietnameseMeaning: text("vietnamese_meaning"), usageNotes: text("usage_notes") }, (table) => [uniqueIndex("vocabulary_meaning_position_unique").on(table.vocabularyId, table.position)]);
export const vocabularyExamples = pgTable("vocabulary_examples", { id: uuid("id").defaultRandom().primaryKey(), vocabularyId: uuid("vocabulary_id").notNull().references(() => vocabularyContent.id, { onDelete: "cascade" }), position: integer("position").notNull(), sentence: text("sentence").notNull(), vietnameseTranslation: text("vietnamese_translation") }, (table) => [uniqueIndex("vocabulary_example_position_unique").on(table.vocabularyId, table.position)]);
export const vocabularyRelations = pgTable("vocabulary_relations", { id: uuid("id").defaultRandom().primaryKey(), sourceVocabularyId: uuid("source_vocabulary_id").notNull().references(() => vocabularyContent.id, { onDelete: "cascade" }), targetWord: text("target_word").notNull(), targetVocabularyId: uuid("target_vocabulary_id").references(() => vocabularyContent.id, { onDelete: "set null" }), relationType: text("relation_type").notNull(), strength: integer("strength"), register: text("register"), usageNote: text("usage_note") }, (table) => [uniqueIndex("vocabulary_relation_unique").on(table.sourceVocabularyId, table.targetWord, table.relationType), index("vocabulary_relation_target_idx").on(table.targetVocabularyId)]);
export const wordFamilies = pgTable("word_families", { id: uuid("id").defaultRandom().primaryKey(), vocabularyId: uuid("vocabulary_id").notNull().references(() => vocabularyContent.id, { onDelete: "cascade" }), word: text("word").notNull(), partOfSpeech: text("part_of_speech").notNull() }, (table) => [uniqueIndex("word_family_unique").on(table.vocabularyId, table.word, table.partOfSpeech)]);
export const collocations = pgTable("collocations", { id: uuid("id").defaultRandom().primaryKey(), contentId: text("content_id").notNull(), phrase: text("phrase").notNull(), level: cefrLevel("level"), meaning: text("meaning"), vietnameseMeaning: text("vietnamese_meaning"), example: text("example"), commonError: text("common_error"), topics: text("topics").array().default([]).notNull(), ...timestamps }, (table) => [uniqueIndex("collocations_content_id_unique").on(table.contentId), index("collocations_phrase_idx").on(table.phrase)]);
export const expressions = pgTable("expressions", { id: uuid("id").defaultRandom().primaryKey(), contentId: text("content_id").notNull(), kind: expressionKind("kind").notNull(), expression: text("expression").notNull(), baseVerb: text("base_verb"), meaning: text("meaning").notNull(), vietnameseMeaning: text("vietnamese_meaning"), level: cefrLevel("level").notNull(), examples: text("examples").array().default([]).notNull(), usageNotes: text("usage_notes"), register: text("register"), separability: text("separability"), topics: text("topics").array().default([]).notNull(), active: boolean("active").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("expressions_content_id_unique").on(table.contentId), index("expressions_kind_level_idx").on(table.kind, table.level), index("expressions_expression_idx").on(table.expression)]);

export const grammarTopics = pgTable("grammar_topics", { id: uuid("id").defaultRandom().primaryKey(), contentId: text("content_id").notNull(), title: text("title").notNull(), level: cefrLevel("level").notNull(), category: text("category").notNull(), description: text("description").notNull(), active: boolean("active").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("grammar_topics_content_id_unique").on(table.contentId), index("grammar_topics_level_idx").on(table.level)]);
export const grammarLessons = pgTable("grammar_lessons", { id: uuid("id").defaultRandom().primaryKey(), grammarTopicId: uuid("grammar_topic_id").notNull().references(() => grammarTopics.id, { onDelete: "cascade" }), englishExplanation: text("english_explanation").notNull(), vietnameseExplanation: text("vietnamese_explanation"), structures: text("structures").array().default([]).notNull(), examples: jsonb("examples").default([]).notNull(), commonMistakes: jsonb("common_mistakes").default([]).notNull(), relatedStructures: text("related_structures").array().default([]).notNull(), contentVersionId: uuid("content_version_id").references(() => contentVersions.id, { onDelete: "set null" }), ...timestamps }, (table) => [uniqueIndex("grammar_lesson_topic_unique").on(table.grammarTopicId)]);
export const grammarPrerequisites = pgTable("grammar_prerequisites", { grammarTopicId: uuid("grammar_topic_id").notNull().references(() => grammarTopics.id, { onDelete: "cascade" }), prerequisiteTopicId: uuid("prerequisite_topic_id").notNull().references(() => grammarTopics.id, { onDelete: "restrict" }) }, (table) => [primaryKey({ columns: [table.grammarTopicId, table.prerequisiteTopicId] }), index("grammar_prerequisite_reverse_idx").on(table.prerequisiteTopicId)]);
export const grammarSubtopics = pgTable("grammar_subtopics", { id: uuid("id").defaultRandom().primaryKey(), grammarTopicId: uuid("grammar_topic_id").notNull().references(() => grammarTopics.id, { onDelete: "cascade" }), contentId: text("content_id").notNull(), title: text("title").notNull(), position: integer("position").notNull() }, (table) => [uniqueIndex("grammar_subtopic_content_unique").on(table.contentId), index("grammar_subtopic_topic_idx").on(table.grammarTopicId)]);
export const exerciseTemplates = pgTable("exercise_templates", { id: uuid("id").defaultRandom().primaryKey(), contentId: text("content_id").notNull(), knowledgeType: knowledgeType("knowledge_type").notNull(), knowledgeContentId: text("knowledge_content_id").notNull(), exerciseType: text("exercise_type").notNull(), difficulty: integer("difficulty").notNull(), template: jsonb("template").notNull(), active: boolean("active").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("exercise_template_content_unique").on(table.contentId), index("exercise_template_knowledge_idx").on(table.knowledgeType, table.knowledgeContentId), check("exercise_difficulty_valid", sql`${table.difficulty} between 1 and 5`)]);
export const placementPassages = pgTable("placement_passages", { id: uuid("id").defaultRandom().primaryKey(), contentId: text("content_id").notNull(), title: text("title").notNull(), passage: text("passage").notNull(), level: cefrLevel("level").notNull(), status: text("status").notNull(), provenanceId: text("provenance_id").notNull(), contentVersionId: uuid("content_version_id").references(() => contentVersions.id, { onDelete: "set null" }), ...timestamps }, (table) => [uniqueIndex("placement_passage_content_unique").on(table.contentId), index("placement_passage_level_status_idx").on(table.level, table.status)]);
export const placementItems = pgTable("placement_items", { id: uuid("id").defaultRandom().primaryKey(), contentId: text("content_id").notNull(), domain: text("domain").notNull(), level: cefrLevel("level").notNull(), topic: text("topic").notNull(), subtopic: text("subtopic").notNull(), prompt: text("prompt").notNull(), options: jsonb("options").notNull(), answer: text("answer").notNull(), explanation: text("explanation").notNull(), difficulty: real("difficulty").notNull(), discrimination: real("discrimination").notNull(), status: text("status").notNull(), provenanceId: text("provenance_id").notNull(), passageContentId: text("passage_content_id"), contentVersionId: uuid("content_version_id").references(() => contentVersions.id, { onDelete: "set null" }), ...timestamps }, (table) => [uniqueIndex("placement_item_content_unique").on(table.contentId), index("placement_item_selection_idx").on(table.status, table.domain, table.level), check("placement_item_parameters_valid", sql`${table.difficulty} between 0 and 1 and ${table.discrimination} between 0.45 and 2.2`)]);

export const reviewStates = pgTable("review_states", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), knowledgeType: knowledgeType("knowledge_type").notNull(), knowledgeContentId: text("knowledge_content_id").notNull(), status: reviewStatus("status").default("new").notNull(), difficulty: real("difficulty").default(5).notNull(), stability: doublePrecision("stability").default(1).notNull(), dueAt: timestamp("due_at", { withTimezone: true }).notNull(), lastReviewedAt: timestamp("last_reviewed_at", { withTimezone: true }), scheduledDays: integer("scheduled_days").default(0).notNull(), elapsedDays: real("elapsed_days").default(0).notNull(), reviewCount: integer("review_count").default(0).notNull(), correctCount: integer("correct_count").default(0).notNull(), incorrectCount: integer("incorrect_count").default(0).notNull(), lapses: integer("lapses").default(0).notNull(), version: integer("version").default(0).notNull(), ...timestamps }, (table) => [uniqueIndex("review_state_user_knowledge_unique").on(table.userId, table.knowledgeType, table.knowledgeContentId), index("review_state_due_idx").on(table.userId, table.dueAt), check("review_state_values_valid", sql`${table.difficulty} between 1 and 10 and ${table.stability} >= 0 and ${table.scheduledDays} >= 0 and ${table.elapsedDays} >= 0 and ${table.reviewCount} >= 0 and ${table.correctCount} >= 0 and ${table.incorrectCount} >= 0 and ${table.lapses} >= 0 and ${table.version} >= 0`)]);
export const vocabularyProgress = pgTable("vocabulary_progress", { userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), vocabularyId: uuid("vocabulary_id").notNull().references(() => vocabularyContent.id, { onDelete: "restrict" }), recognition: integer("recognition").default(0).notNull(), recall: integer("recall").default(0).notNull(), context: integer("context").default(0).notNull(), spelling: integer("spelling").default(0).notNull(), overall: integer("overall").default(0).notNull(), ...timestamps }, (table) => [primaryKey({ columns: [table.userId, table.vocabularyId] }), index("vocabulary_progress_user_idx").on(table.userId), check("vocabulary_mastery_valid", sql`${table.recognition} between 0 and 100 and ${table.recall} between 0 and 100 and ${table.context} between 0 and 100 and ${table.spelling} between 0 and 100 and ${table.overall} between 0 and 100`)]);
export const grammarProgress = pgTable("grammar_progress", { userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), grammarTopicId: uuid("grammar_topic_id").notNull().references(() => grammarTopics.id, { onDelete: "restrict" }), mastery: integer("mastery").default(0).notNull(), subtopicMastery: jsonb("subtopic_mastery").default({}).notNull(), ...timestamps }, (table) => [primaryKey({ columns: [table.userId, table.grammarTopicId] }), index("grammar_progress_user_idx").on(table.userId), check("grammar_mastery_valid", sql`${table.mastery} between 0 and 100`)]);
export const expressionProgress = pgTable("expression_progress", { userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), expressionId: uuid("expression_id").notNull().references(() => expressions.id, { onDelete: "restrict" }), mastery: integer("mastery").default(0).notNull(), ...timestamps }, (table) => [primaryKey({ columns: [table.userId, table.expressionId] }), check("expression_mastery_valid", sql`${table.mastery} between 0 and 100`)]);
export const mistakes = pgTable("mistakes", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), knowledgeType: knowledgeType("knowledge_type").notNull(), knowledgeContentId: text("knowledge_content_id").notNull(), subtopicContentId: text("subtopic_content_id"), exerciseType: text("exercise_type").notNull(), question: text("question").notNull(), userAnswer: text("user_answer").notNull(), correctAnswer: text("correct_answer").notNull(), repeatCount: integer("repeat_count").default(1).notNull(), resolved: boolean("resolved").default(false).notNull(), lastOccurredAt: timestamp("last_occurred_at", { withTimezone: true }).defaultNow().notNull(), ...timestamps }, (table) => [uniqueIndex("mistakes_user_exercise_unique").on(table.userId, table.knowledgeType, table.knowledgeContentId, table.exerciseType), index("mistakes_user_active_idx").on(table.userId, table.resolved), index("mistakes_user_knowledge_idx").on(table.userId, table.knowledgeType, table.knowledgeContentId), check("mistake_repeat_count_valid", sql`${table.repeatCount} > 0`)]);
export const studySessions = pgTable("study_sessions", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), idempotencyKey: text("idempotency_key").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), completedAt: timestamp("completed_at", { withTimezone: true }), correct: integer("correct").default(0).notNull(), total: integer("total").default(0).notNull(), minutes: integer("minutes").default(0).notNull(), summary: jsonb("summary").default({}).notNull() }, (table) => [uniqueIndex("study_session_user_idempotency_unique").on(table.userId, table.idempotencyKey), index("study_session_user_date_idx").on(table.userId, table.startedAt), check("study_session_counts_valid", sql`${table.correct} >= 0 and ${table.total} >= ${table.correct} and ${table.minutes} >= 0`), check("study_session_time_valid", sql`${table.completedAt} is null or ${table.completedAt} >= ${table.startedAt}`)]);
export const studySessionItems = pgTable("study_session_items", { id: uuid("id").defaultRandom().primaryKey(), studySessionId: uuid("study_session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }), knowledgeType: knowledgeType("knowledge_type").notNull(), knowledgeContentId: text("knowledge_content_id").notNull(), exerciseType: text("exercise_type").notNull(), answer: text("answer"), correct: boolean("correct"), rating: text("rating"), position: integer("position").notNull(), reviewVersion: integer("review_version") }, (table) => [uniqueIndex("study_session_item_position_unique").on(table.studySessionId, table.position)]);
export const placementAttempts = pgTable("placement_attempts", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), idempotencyKey: text("idempotency_key").notNull(), estimatedLevel: cefrLevel("estimated_level"), overallAbility: real("overall_ability"), standardError: real("standard_error"), confidenceScore: integer("confidence_score"), confidenceLabel: text("confidence_label"), dimensionScores: jsonb("dimension_scores"), domainEstimates: jsonb("domain_estimates"), topicScores: jsonb("topic_scores"), strongAreas: text("strong_areas").array().default([]).notNull(), weakAreas: text("weak_areas").array().default([]).notNull(), startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(), completedAt: timestamp("completed_at", { withTimezone: true }) }, (table) => [uniqueIndex("placement_user_idempotency_unique").on(table.userId, table.idempotencyKey), index("placement_user_date_idx").on(table.userId, table.completedAt), check("placement_confidence_valid", sql`${table.confidenceScore} is null or ${table.confidenceScore} between 0 and 100`)]);
export const placementAnswers = pgTable("placement_answers", { placementAttemptId: uuid("placement_attempt_id").notNull().references(() => placementAttempts.id, { onDelete: "cascade" }), questionId: text("question_id").notNull(), answer: text("answer").notNull(), correct: boolean("correct").notNull(), level: cefrLevel("level").notNull(), dimension: text("dimension").notNull(), topic: text("topic").notNull(), subtopic: text("subtopic"), difficulty: real("difficulty"), discrimination: real("discrimination"), responseTimeMs: integer("response_time_ms"), position: integer("position").notNull() }, (table) => [primaryKey({ columns: [table.placementAttemptId, table.questionId] }), uniqueIndex("placement_answer_position_unique").on(table.placementAttemptId, table.position), check("placement_answer_parameters_valid", sql`(${table.difficulty} is null or ${table.difficulty} between 0 and 1) and (${table.discrimination} is null or ${table.discrimination} between 0.45 and 2.2) and (${table.responseTimeMs} is null or ${table.responseTimeMs} >= 0)`)]);
export const learningPaths = pgTable("learning_paths", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), version: integer("version").default(1).notNull(), generatedAt: timestamp("generated_at", { withTimezone: true }).defaultNow().notNull(), inputs: jsonb("inputs").default({}).notNull(), active: boolean("active").default(true).notNull() }, (table) => [index("learning_path_user_active_idx").on(table.userId, table.active)]);
export const learningPathItems = pgTable("learning_path_items", { id: uuid("id").defaultRandom().primaryKey(), learningPathId: uuid("learning_path_id").notNull().references(() => learningPaths.id, { onDelete: "cascade" }), knowledgeType: knowledgeType("knowledge_type").notNull(), knowledgeContentId: text("knowledge_content_id").notNull(), status: pathItemStatus("status").notNull(), priority: integer("priority").notNull(), reason: text("reason").notNull(), position: integer("position").notNull() }, (table) => [uniqueIndex("learning_path_item_unique").on(table.learningPathId, table.knowledgeType, table.knowledgeContentId), index("learning_path_item_order_idx").on(table.learningPathId, table.position)]);

/** Temporary, versioned bridge for explicit migration from the existing browser-local AppState. */
export const userStateSnapshots = pgTable("user_state_snapshots", { userId: uuid("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), schemaVersion: integer("schema_version").default(1).notNull(), state: jsonb("state").notNull(), importedLegacyAt: timestamp("imported_legacy_at", { withTimezone: true }), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }), action: text("action").notNull(), entityType: text("entity_type"), entityId: text("entity_id"), metadata: jsonb("metadata").default({}).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("audit_log_user_date_idx").on(table.userId, table.createdAt), index("audit_log_action_idx").on(table.action)]);
