"use client";

import { useState } from "react";
import { BookOpen, Search, SlidersHorizontal } from "lucide-react";
import { vocabulary } from "@/data/vocabulary";
import { useAppState } from "@/components/app-provider";
import { PageHeader, ProgressBar } from "@/components/ui";

export default function VocabularyPage() {
  const { state } = useAppState(); const [query, setQuery] = useState(""); const [level, setLevel] = useState("All"); const [status, setStatus] = useState("All"); const [part, setPart] = useState("All"); const [topic, setTopic] = useState("All"); const [page, setPage] = useState(1);
  const PAGE_SIZE = 24; const progressById = new Map(state.vocabularyProgress.map((item) => [item.itemId, item])); const normalizedQuery = query.trim().toLocaleLowerCase();
  const filtered = vocabulary.filter((item) => { const progress = progressById.get(item.id); const statusMatches = status === "All" || (status === "Unseen" && !progress) || (status === "Mastered" && Boolean(progress && progress.mastery.overall >= 85)) || (status === "Learning" && Boolean(progress && progress.mastery.overall < 85)); const searchable = [item.word, ...item.meanings.flatMap((meaning) => [meaning.definition, meaning.vietnamese ?? ""]), ...(item.topics ?? []), ...item.synonyms.map((relation) => relation.word), ...item.collocations].join(" ").toLocaleLowerCase(); return (level === "All" || item.cefrLevel === level) && (part === "All" || item.partOfSpeech === part) && (topic === "All" || item.topics?.includes(topic)) && statusMatches && searchable.includes(normalizedQuery); });
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((Math.min(page, pageCount) - 1) * PAGE_SIZE, Math.min(page, pageCount) * PAGE_SIZE);
  const updateFilter = (setter: (value: string) => void) => (value: string) => { setter(value); setPage(1); };
  return <><PageHeader eyebrow={`${vocabulary.length} curated words`} title="Vocabulary" description="Learn meaning, recall, context, and spelling separately—because knowing a word is more than recognizing it."/>
    <div className="card mb-4 grid gap-3 p-3 sm:grid-cols-2 xl:grid-cols-[1fr_auto_auto_auto_auto]"><label className="flex items-center gap-2 rounded-xl bg-[#f5f8f6] px-3"><Search size={17} className="muted"/><span className="sr-only">Search vocabulary</span><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} className="h-11 w-full bg-transparent text-sm outline-none" placeholder="Search words, meanings, topics…"/></label><Filter value={level} onChange={updateFilter(setLevel)} label="CEFR" options={["All", "A1", "A2", "B1", "B2", "C1", "C2"]}/><Filter value={part} onChange={updateFilter(setPart)} label="Part of speech" options={["All", ...new Set(vocabulary.map((item) => item.partOfSpeech))]}/><Filter value={topic} onChange={updateFilter(setTopic)} label="Topic" options={["All", ...new Set(vocabulary.flatMap((item) => item.topics ?? []))]}/><Filter value={status} onChange={updateFilter(setStatus)} label="Learning status" options={["All", "Unseen", "Learning", "Mastered"]}/></div>
    {filtered.length === 0 && <div className="card p-10 text-center"><h2 className="font-extrabold">No matching words</h2><p className="muted mt-1 text-sm">Try another search or CEFR level.</p></div>}
    <div className="grid gap-3 xl:grid-cols-2">{visible.map((item) => { const progress = progressById.get(item.id); const mastery = progress?.mastery; return <article key={item.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-extrabold">{item.word}</h2><span className="badge">{item.cefrLevel}</span><span className="muted text-xs">{item.partOfSpeech}</span>{item.ipa && <span className="muted text-xs">/{item.ipa}/</span>}</div><p className="mt-1 text-sm">{item.meanings[0].definition}</p>{state.settings.showVietnamese && <p className="mt-1 text-sm font-semibold text-[#17795b]">{item.meanings[0].vietnamese}</p>}</div><BookOpen size={19} className="text-[#17795b]"/></div><p className="muted mt-4 border-l-2 border-[#badbce] pl-3 text-sm italic">“{item.examples[0]}”</p>{item.collocations.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{item.collocations.map((text) => <span className="badge" key={text}>{text}</span>)}</div>}<div className="mt-5 grid grid-cols-2 gap-x-4 gap-y-3">{(["recognition", "recall", "context", "spelling"] as const).map((dimension) => <div key={dimension}><div className="mb-1 flex justify-between text-[11px] font-bold capitalize"><span>{dimension}</span><span className="muted">{mastery?.[dimension] ?? 0}%</span></div><ProgressBar value={mastery?.[dimension] ?? 0}/></div>)}</div>{(item.synonyms.length > 0 || item.antonyms.length > 0 || item.wordFamily.length > 0) && <details className="mt-4 rounded-xl bg-[#f5f8f6] p-3 text-sm"><summary className="cursor-pointer font-bold text-[#17795b]">Relations and nuance</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{item.synonyms.length > 0 && <div><b className="text-xs uppercase tracking-wide">Synonyms</b>{item.synonyms.map((relation) => <p key={relation.word} className="muted mt-1 text-xs"><strong className="text-[#15241f]">{relation.word}</strong> · strength {relation.strength}%{relation.notes ? ` — ${relation.notes}` : ""}</p>)}</div>}{item.antonyms.length > 0 && <div><b className="text-xs uppercase tracking-wide">Antonyms</b><p className="muted mt-1 text-xs">{item.antonyms.map((relation) => relation.word).join(", ")}</p></div>}{item.wordFamily.length > 0 && <div><b className="text-xs uppercase tracking-wide">Word family</b><p className="muted mt-1 text-xs">{item.wordFamily.map((relation) => `${relation.word} (${relation.partOfSpeech})`).join(", ")}</p></div>}</div></details>}<div className="mt-4 flex justify-between border-t border-[#e2eae6] pt-3 text-xs"><span className="muted">{progress ? `Next review ${new Date(progress.review.nextReview).toLocaleDateString()}` : "New · ready to learn"}</span><b>{mastery?.overall ?? 0}% overall</b></div></article>; })}</div>
    {filtered.length > PAGE_SIZE && <nav aria-label="Vocabulary pages" className="mt-5 flex items-center justify-center gap-3"><button className="btn-secondary" disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>Previous</button><span className="muted text-sm">Page {Math.min(page, pageCount)} of {pageCount} · {filtered.length} words</span><button className="btn-secondary" disabled={page >= pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))}>Next</button></nav>}
  </>;
}

function Filter({ value, onChange, label, options }: { value: string; onChange: (value: string) => void; label: string; options: string[] }) { return <label className="flex items-center gap-2 rounded-xl border border-[#dce6e1] px-3"><SlidersHorizontal size={16}/><span className="sr-only">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-11 bg-transparent text-sm font-bold outline-none">{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
