"use client";

import { useState } from "react";
import { expressions } from "@/data/expressions";
import { PageHeader } from "@/components/ui";
import { useAppState } from "@/components/app-provider";

const kinds = ["all", "idiom", "phrasal-verb", "collocation", "common-expression"] as const;
export default function ExpressionsPage() {
  const { state } = useAppState(); const [filter, setFilter] = useState<(typeof kinds)[number]>("all"); const [level, setLevel] = useState("All"); const [category, setCategory] = useState("All");
  const categories = ["All", ...new Set(expressions.flatMap((item) => item.tags))];
  const items = expressions.filter((item) => (filter === "all" || item.kind === filter) && (level === "All" || item.cefrLevel === level) && (category === "All" || item.tags.includes(category)));
  return <><PageHeader eyebrow={`${expressions.length} natural expressions`} title="Expressions" description="Study idioms, phrasal verbs, collocations, and everyday expressions with context and usage notes."/><div className="mb-3 flex gap-2 overflow-x-auto pb-1">{kinds.map((kind) => <button key={kind} onClick={() => setFilter(kind)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-extrabold capitalize ${filter === kind ? "bg-[#17795b] text-white" : "bg-white ring-1 ring-[#dce6e1]"}`}>{kind.replace("-", " ")}</button>)}</div><div className="card mb-5 flex flex-wrap gap-3 p-3"><label className="text-xs font-bold">CEFR <select value={level} onChange={(event) => setLevel(event.target.value)} className="ml-2 rounded-lg border border-[#dce6e1] bg-white p-2"><option>All</option>{["A1", "A2", "B1", "B2", "C1", "C2"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs font-bold">Category <select value={category} onChange={(event) => setCategory(event.target.value)} className="ml-2 rounded-lg border border-[#dce6e1] bg-white p-2">{categories.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="grid gap-3 lg:grid-cols-2">{items.map((item) => <article className="card p-5" key={item.id}><div className="flex items-center gap-2"><span className="badge capitalize">{item.kind.replace("-", " ")}</span><span className="muted text-xs font-bold">{item.cefrLevel}</span>{item.separability && <span className="muted text-xs">· {item.separability}</span>}</div><h2 className="mt-3 text-xl font-extrabold">{item.expression}</h2><p className="mt-2 text-sm">{item.meaning}</p>{state.settings.showVietnamese && <p className="mt-1 text-sm font-semibold text-[#17795b]">{item.vietnameseMeaning}</p>}<p className="muted mt-4 border-l-2 border-[#badbce] pl-3 text-sm italic">“{item.examples[0]}”</p><div className="mt-4 rounded-xl bg-[#f5f8f6] p-3 text-xs"><b>Usage note</b><p className="muted mt-1">{item.usageNotes}</p></div></article>)}</div></>;
}
