"use client";

import { useState } from "react";
import { Check, LockKeyhole, Route } from "lucide-react";
import { grammarTopics, curriculumOutline } from "@/data/grammar";
import { useAppState } from "@/components/app-provider";
import { prerequisitesMet } from "@/lib/learning/prerequisites";
import { PageHeader, ProgressBar } from "@/components/ui";

export default function GrammarPage() {
  const { state } = useAppState();
  const [level, setLevel] = useState(state.settings.currentLevel);
  const visibleTopics = grammarTopics.filter((item) => item.level === level);
  return <><PageHeader eyebrow="A1 → C2 curriculum" title="Grammar" description="Move through a prerequisite-aware path while tracking specific weak subtopics, not just whole lessons."/>
    <section className="card mb-5 overflow-hidden p-5"><div className="mb-4 flex items-center gap-2"><Route size={19} className="text-[#17795b]"/><h2 className="font-extrabold">Curriculum map</h2></div><div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{Object.entries(curriculumOutline).map(([itemLevel, items], index) => <button type="button" onClick={() => setLevel(itemLevel as typeof level)} key={itemLevel} aria-pressed={level === itemLevel} className={`rounded-xl border p-3 text-left ${level === itemLevel ? "border-[#17795b] bg-[#e8f6f0]" : "border-[#e2eae6] bg-white"}`}><b>{itemLevel}</b><div className="muted mt-1 text-xs">{items.length} concepts</div><div className="mt-2 text-[10px] font-bold text-[#17795b]">{index < 2 ? "FOUNDATION" : index < 4 ? "INDEPENDENT" : "PROFICIENT"}</div></button>)}</div></section>
    <div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-extrabold">{level} topics</h2><span className="badge">{visibleTopics.length} topics</span></div>
    <div className="grid gap-3 lg:grid-cols-2">{visibleTopics.map((item) => { const progress = state.grammarProgress.find((entry) => entry.topicId === item.id); const unlocked = prerequisitesMet(item, state.grammarProgress); const status = !unlocked ? "Locked" : !progress ? "Ready" : progress.mastery >= 85 ? "Mastered" : progress.mastery >= 70 ? "Strong" : progress.mastery < 50 ? "Weak" : "Learning"; return <article key={item.id} className={`card p-5 ${!unlocked ? "opacity-65" : ""}`}><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex gap-2"><span className="badge">{status}</span><span className="muted text-xs font-bold">{item.category}</span></div><h2 className="text-lg font-extrabold">{item.title}</h2><p className="muted mt-1 text-sm">{item.description}</p></div><span className={`grid size-9 shrink-0 place-items-center rounded-full ${unlocked ? "bg-[#e8f6f0] text-[#17795b]" : "bg-slate-100 text-slate-500"}`}>{unlocked ? <Check size={18}/> : <LockKeyhole size={16}/>}</span></div>{progress && <><div className="mt-4 flex items-center gap-3"><div className="flex-1"><ProgressBar value={progress.mastery}/></div><b className="text-sm">{progress.mastery}%</b></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{item.subtopics.map((subtopic) => <div key={subtopic.id} className="flex items-center justify-between rounded-lg bg-[#f5f8f6] px-2.5 py-2 text-xs"><span>{subtopic.title}</span><b>{progress.subtopicMastery[subtopic.id] ?? 0}%</b></div>)}</div></>} {!progress && <div className="muted mt-4 text-xs">{unlocked ? "Ready to begin" : `Requires ${item.prerequisites.map((id) => grammarTopics.find((topic) => topic.id === id)?.title ?? id).join(", ")}`}</div>}{unlocked && <details className="mt-4 border-t border-[#e2eae6] pt-3"><summary className="cursor-pointer text-sm font-bold text-[#17795b]">Lesson preview</summary><p className="muted mt-3 text-sm leading-relaxed">{item.explanation}</p><div className="mt-3 rounded-xl bg-[#f5f8f6] p-3"><b className="text-xs uppercase tracking-wide">Structure</b><p className="mt-1 text-sm">{item.structures.join(" · ")}</p></div><div className="mt-2 rounded-xl bg-red-50 p-3 text-sm"><b>Common mistake</b><p className="mt-1"><span className="text-red-700 line-through">{item.commonMistakes[0].incorrect}</span><span className="mx-2">→</span><span className="font-bold text-emerald-700">{item.commonMistakes[0].correct}</span></p><p className="muted mt-1 text-xs">{item.commonMistakes[0].explanation}</p></div></details>}</article>; })}</div>
  </>;
}
